### ISSUE TITLE
support for OLS 4?

### ISSUE THREAD

**Issue by azankl** [lgatto/rols#36]
EBI apparently stopped updating ontologies in OLS 3 at the end of 2022, new versions of ontologies are only available in OLS 4.
For example, the MONDO ontology in OLS 3 is version 2022-12-01, but the MONDO version in OLS 4 is 2023-04-04.
rols still seems to query OLS 3, could you update it to use OLS 4?

**Comment by lgatto** [comment]
Thank you, I missed this completely. I will have to read about it and probably have to re-write `rols` completely to make use of their new API. I will look into it as soon as possible.

**Comment by grlloyd** [comment]
@lgatto Builds of rols on both release and devel versions of Bioconductor are failing, I think because EBI has officially moved over to OLS4 and the url has changed, amongst other things. One of the packages I maintain has rols as a dependency, so my builds are failing on devel as well. Do you think a fix will be in place in time for the next Bioconductor release (Apr 2024)?

**Comment by lgatto** [comment]
I'm working on - see the [ols4](https://github.com/lgatto/rols/tree/ols4) branch.

**Comment by lgatto** [comment]
A new version, 2.99, is now available. You can install it from github now, and from Bioc in 24 hours or so.

```
BiocManager::install("lgatto/rols")
```
